# client.toml
[client]
remote_addr = "myserver.com:2333" # 服务器的地址。端口必须与 `server.bind_addr` 中的端口相同。

[client.services.my_nas_ssh]
local_addr = "127.0.0.1:22" # 需要被转发的服务的地址
token = "use_a_secret_that_only_you_know" # 必须与服务器相同以通过验证
